server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: sample-springboot-app

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#The following properties are needed for pushing the application metrics to OCI 
oci:
  useInstancePrincipal: false
  #OCI config file path
  ociConfigPath: C:\Users\SBUDDE\.oci\config
  #OCI profile name
  ociProfile: DEFAULT
  #OCID of the compartment where the metrics need to be pushed
  metricsCompartmentOcid: ocid1.compartment.oc1..aaaaaaaaehvvkog4ms6ctdwpckbhrxnjqhhbt6cqkbpiafuv7cyzoy77slxa
  #namespace to be created in OCI for the application metrics
  metricsNamespace: oke_springboot_app
  # Time interval for pushing the metrics to OCI. The value is in milliseconds
  metricsPushInterval: 10000
