server:
  port: 8080

spring:
  application:
    name: sample-springboot-app

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#The following properties are needed for pushing the application metrics to OCI 
oci:
  useInstancePrincipal: ${OCI_USE_INSTANCE_PRINCIPAL}
  #OCI config file path
  ociConfigPath: ${OCI_CONFIG_PATH}
  #OCI profile name
  ociProfile: ${OCI_PROFILE_NAME}
  #OCID of the compartment where the metrics need to be pushed
  metricsCompartmentOcid: ${OCI_METRICS_COMPARTMENT_ID}
  #namespace to be created in OCI for the application metrics
  metricsNamespace: ${OCI_METRICS_NAMESPACE}
  # Time interval for pushing the metrics to OCI. The value is in milliseconds
  metricsPushInterval: ${OCI_METRICS_PUSH_INTERVAL}
  # Metrics Target Region Endpoint URL
  metricsEndpoint: ${OCI_METRICS_ENDPOINT}
