apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-config
data:
  oci-config.json: >-
    {
    "OCI_USE_INSTANCE_PRINCIPAL": true, 
    "OCI_CONFIG_PATH": "~/.oci/config",
    "OCI_PROFILE_NAME": "DEFAULT", 
    "OCI_METRICS_COMPARTMENT_ID": "", 
    "OCI_METRICS_NAMESPACE": "oke_springboot_app", 
    "OCI_METRICS_PUSH_INTERVAL": "10000",
    "OCI_METRICS_ENDPOINT": "https://telemetry-ingestion.eu-frankfurt-1.oraclecloud.com" 
    }
