kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myvolume22
  annotations:
    volume.beta.kubernetes.io/oci-volume-source: ocid1.volume.oc1.eu-frankfurt-1.abtheljsyr6afas6r4gflgnhrxlhsheu252pdkkxi52vgwlbczzgdp75c2nq
spec:
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: EU-FRANKFURT-1-AD-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
